org.gradle.caching=true
group=io.ballerina.lib
version=1.0.1-SNAPSHOT

releasePluginVersion=3.1.0
ballerinaGradlePluginVersion=4.0.0
spotbugsPluginVersion=6.5.1
shadowJarPluginVersion=8.1.1
downloadPluginVersion=5.4.0

ballerinaLangVersion=2201.13.5-20260717-102000-26087aa2
jacocoVersion=0.8.14

stdlibIoVersion=1.8.0
stdlibTimeVersion=2.7.0
stdlibObserveVersion=1.5.0

stdlibCryptoVersion=2.9.0
stdlibLogVersion=2.12.0
stdlibTaskVersion=2.10.0

stdlibUuidVersion=1.10.0
